require 'net/http'
require 'uri'
require 'json'

class Ip2kml

  def initialize(ip_list)
    @geoip_service_base_url = 'http://www.freegeoip.net/json/'
    @ip_list = ip_list
    @kml_file_data = String.new  # This will get populated with the XML text
  end

  def get_ip_info(ip_address)
    # Look up IP information from web service
    uri = URI.parse(@geoip_service_base_url + ip_address)
    response = Net::HTTP.get_response(uri)
    JSON.parse(response.body)
  end

  def generate_pin_from_ip(ip_address)
    ip_data = get_ip_info(ip_address)
    @kml_file_data << <<EOT
    <Placemark>
      <name>#{ip_data['ip']}</name>
        <description>
        </description>
      <Point>
        <coordinates>#{ip_data['longitude']},#{ip_data['latitude']},0</coordinates>
      </Point>
    </Placemark>
EOT
  end

  def start_kml_file
    # Header boilerplate of KML file
    @kml_file_data = <<EOT
<?xml version="1.0" encoding="UTF-8"?>
  <kml xmlns="http://www.opengis.net/kml/2.2">'
EOT
  end

  def finish_kml_file
    # Footer boilerplate for KML file
    @kml_file_data << <<EOT
</kml> <!-- Auto generated by ip2kml -->
EOT
  end

  def generate_kml_file
    start_kml_file
    @ip_list.each do |ip_address|
      generate_pin_from_ip(ip_address.strip!)
    end
    finish_kml_file
    return
  end

  def get_kml_file
    return @kml_file_data
  end

end
